# Generated by Django 3.0.3 on 2020-05-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200528_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
