# Generated by Django 3.0.3 on 2020-05-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_template_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
