# Generated by Django 3.0.3 on 2020-05-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200528_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_need_domain',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_need_hosting',
        ),
        migrations.AddField(
            model_name='order',
            name='is_need_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_need_hosting',
            field=models.BooleanField(default=False),
        ),
    ]
